<a href="https://colab.research.google.com/github/sajillidhan123/Data-Science-Lab/blob/main/CO_1_Matrix_Operations_Sajil_Lidhan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x=np.matrix('1 2 3;4 5 6;7 8 9')
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
x=np.matrix('8 7;3 -5')
y=np.matrix('3;2')
multiplied=np.matmul(x,y)
multiplied

matrix([[38],
        [-1]])

**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
identity_matrix=np.identity(5,dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
x=np.matrix('1 2 3;4 5 6;7 8 9')
identity_matrix=np.identity(3,dtype=int)
multiplied=np.matmul(x,identity_matrix)
multiplied

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
a=np.matrix('1 3 3;1 4 3;1 3 4')
b=np.matrix('7 -3 -3;-1 1 0;-1 0 1')
inverse=np.matmul(a,b)
inverse

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
x=np.matrix('8 7;3 -5')
detmat=np.linalg.det(x)
detmat

-60.99999999999995

Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A.
a=np.matrix('1 3 3;1 4 3;1 3 4')
detmat=np.linalg.det(a)
detmat

1.0

In [ ]:
# Calculate the inverse of the above matrix A.
a=np.matrix('1 3 3;1 4 3;1 3 4')
inverse=np.linalg.inv(a)
inverse

matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [ ]:
#Create a dictionary to store weatherdata and convert it to a dataframe
import pandas as pd
weatherdata={
'Day':['1/10/15','2/11/12','13/05/21','12/08/16','14/07/21'],
'City':['Calicut','Kottayam','Wayanad','Malappuram','Trivandrum'],
'Temp':['30.2','25.9','31.6','28.2','34.9'],
'Windspeed':['60','120','85','140','90']}
weatherdata=pd.DataFrame(weatherdata)
# Display the first five rows of dataframe
weatherdata.head()

#Display the last five rows of dataframe
weatherdata.tail()


Day        City  Temp Windspeed
0   1/10/15     Calicut  30.2        60
1   2/11/12    Kottayam  25.9       120
2  13/05/21     Wayanad  31.6        85
3  12/08/16  Malappuram  28.2       140
4  14/07/21  Trivandrum  34.9        90